# GraphQL: Directives

## Introduction

A GraphQL schema describes directives which are used to annotate various parts of a GraphQL document as an indicator that 
they should be evaluated differently by a validator, executor, or client tool such as a code generator.
GraphQL implementations should provide the @skip and @include directives.
GraphQL implementations that support the type system definition language must provide the  @deprecated directive if 
representing deprecated portions of the schema.
Directives must only be used in the locations they are declared to belong in. In this example, a directive is defined 
which can be used to annotate a field: [facebook.github.io/graphql](https://facebook.github.io/graphql/draft/#sec-Type-System.Directives) 

Authorization is a good and common scenario in which we usually will make use of directives. We could control what
users are allowd to fetch an object (or even an attribute) from the server.

```graphql

directive @isAuthenticated on FIELD | FIELD_DEFINITION
directive @hasRole(role: String) on FIELD | FIELD_DEFINITION


```

or for clients tools as It was mentioned on the above paragraph.

```graphql
directive @deprecated(
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE


type ExampleType {
  newField: String
  oldField: String @deprecated(reason: "Use `newField`.")
}

```


## Code

When defining a directive we need to define its scope. Have a look at [apollographql.com](https://www.apollographql.com/docs/graphql-tools/schema-directives.html) to understand
how to implement our own directives.

Below a very basic example of directive.

**directives.js**
```js
import { SchemaDirectiveVisitor } from "graphql-tools";

class DeprecatedDirective extends SchemaDirectiveVisitor {
  
  visitFieldDefinition(field) {
    field.isDeprecated = true;
    field.deprecationReason = this.args.reason;
  }

  visitEnumValue(value) {
    value.isDeprecated = true;
    value.deprecationReason = this.args.reason;
  }
}
```

Once we've implemented the directive ,  we just need to add the directives as shown below:

**src/schema.js**
```js
export default makeExecutableSchema({
    typeDefs,
    resolvers,
    schemaDirectives: {
        dreprecated: DeprecatedDirective,
        
    },
    ...
});
```

## Challenges

1. Create a directive @multiply with an attribute factor. The directive declaration
should look like this

```graphql
directive @multiply (
    factor: Int!
) on FIELD_DEFINITION
```
And this directive will be used for attribute rate in type Movie. The behavior will be the following: If factor is 2
the returned budget will be the real value multiply by 2. If the factor is 3 the returned value will be
the budget multiplied by 3...

```graphql
input Movie {
    ...
    rate:Float @multiply(factor:5)
    ...
}
```

To verify run this query 

```graphql
query {
  rate: getMovieRate(movieId:1){
    realRate: rate
  }
  movie: getMovie(movieId:1){
    customRate: rate
    
  }
}
```

and verify that customRate is the value of realRate multiplied by 5

```json
{
  "data": {
    "rate": {
      "realRate": 3
    },
    "movie": {
      "customRate": 15
    }
  }
}
```
